---

- hosts: all
  roles:
    - role: contrail-rh-reg
      vars:
        rh_reg_mode: unregister
      when: ansible_distribution == "RedHat"

- hosts: all
  roles:
    - fetch-artifacts

# NOTE: here was site_pulp host
- hosts: localhost
  roles:
    - contrail-common-libs2
    - upload-artifacts
