---

- hosts: all
  roles:
    - contrail-common-libs2
    - configure-hosts-entries
    - role: contrail-rh-reg
      vars:
        rh_reg_mode: register
      when: ansible_distribution == "RedHat"

- hosts: all
  roles:
    - role: configure-hosts-entries
      hosts_entries:
        - fqdn: "{{ ansible_fqdn }}"
          address: "{{ ansible_all_ipv4_addresses[0] }}"

- hosts: localhost
  roles:
    - zuul-include-vars
    - setup-docker-registry
