---

- hosts: all
  roles:
    - contrail-common-libs2
    - configure-hosts-entries

- hosts: all
  roles:
    - role: configure-hosts-entries
      hosts_entries:
        - fqdn: "{{ ansible_fqdn }}"
          address: "{{ ansible_all_ipv4_addresses[0] }}"

# NOTE: here was site_pulp host
- hosts: localhost
  roles:
    - zuul-include-vars
    - setup-docker-registry

