---

- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"

- name: return repository location back to zuul for children jobs
  zuul_return:
    data:
      contrail_container_tag: '{{ packaging.docker_version }}'
