---

- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "{{ zuul_log_url }}"

- hosts: all
  roles:
    - acquire-ip-address
    - disable-os-unattended-upgrades
    - add-build-sshkey
    - validate-host
    - configure-hosts-entries
    - configure-mirrors-contrail
    - gitlog-upload
- hosts: all
  roles:
    - role: configure-hosts-entries
      hosts_entries:
        - fqdn: "{{ ansible_fqdn }}"
          address: "{{ ansible_all_ipv4_addresses[0] }}"

