---
- name: Register RHEL host
  command: subscription-manager register {{ lookup('file', '/etc/zuul/rh_reg_options') }}
#  no_log: true
  when: rh_reg_mode == "register"
  register: rh_reg
  failed_when: false

- name: debug RHEL registration
  debug:
    msg: "{{ rh_reg }}"

- fail:
  when: rh_reg.rc != 0

- name: Unregister RHEL host
  command: subscription-manager unregister
  when: rh_reg_mode == "unregister"
