---
- name: Register RHEL host
  command: subscription-manager register {{ lookup('file', '/etc/zuul/rh_reg_options') }}
#  no_log: true
  register: rh_reg
  become: true
  when: rh_reg_mode == "register"
  failed_when: false

- name: debug RHEL registration
  debug:
    msg: |
      "{{ rh_reg.stdout | default('') }}"
      "{{ rh_reg.stderr | default('') }}"
  when: rh_reg_mode == "register"

- name: Ensure docker config dir
  file:
    path: /root/.docker
    owner: root
    group: root
    mode: 700
    state: directory
  become: true
  when: rh_reg_mode == "register"

- name: Set up docker config file
  copy:
    src: /etc/zuul/docker_rh_config
    dest: /root/.docker/config.json
    owner: root
    group: root
    mode: 0600
  become: true
  when: rh_reg_mode == "register"

- name: Unregister RHEL host
  command: subscription-manager unregister
  become: true
  when: rh_reg_mode == "unregister"
