---

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - epel-release
    - python36

- name: install virtualenv for publisher
  command: python36 -m venv venv
  args:
    chdir: "{{ publisher_path }}"

- name: install requirements
  shell: |
    . venv/bin/activate
    pip install -r requirements.txt
  args:
    chdir: "{{ publisher_path }}"

- name: copy publisher config
  copy:
    src: publisher-{{ item }}-config.yaml
    dest: "{{ publisher_path }}/publisher-{{ item }}-config.yaml"
  with_items:
    - internal
    - dockerhub

- name: Push to internal registry
  shell: |
    . venv/bin/activate
    python36 publisher.py --config publisher-internal-config.yaml --build-registry {{ contrail_docker_registry }} --release {{ contrail_packaging.version.public }} --build {{ build_number }} --openstack_release {{ item }}
  become: true
  args:
    chdir: "{{ publisher_path }}"
  with_items:
    - newton
    - ocata
    - queens
    - rocky

- name: Show the list of docker images
  command: docker images
  become: true

