---

- name: Prepare packaging variable
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "nightly"

- name: Print the packaging variables
  debug:
    var: packaging

- name: Generate the build number
  debugger: always
  ignore_errors: true
  build_number:
    zuul_buildset_id: "{{ zuul.buildset }}"
    version: "{{ packaging.version.public }}"
    build_cache_db_connection_info: "{{ build_cache_db }}"

- set_fact:
    build_number: "{{ build_number | default('latest') }}"

- name: Print the packaging variables
  debug:
    var: build_number

- name: Save the build tag for subsequent jobs in the pipeline
  zuul_return:
    data:
      build_number: "{{ build_number }}"

