---

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - ara-report

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: false
  roles:
    - role: upload-logs
      zuul_log_url: "{{ zuul_log_url }}"
      zuul_logserver_root: "/var/www/logs"
