---

- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "{{ zuul_log_url }}"

- hosts: all
  roles:
    - add-build-sshkey
    - configure-hosts-entries
    - configure-mirrors
    - role: configure-maven-proxy
      maven_repo_mirror_url: 'http://{{ nexus.fqdn }}/repository/{{ nexus.repos.maven }}/'
    - validate-host
    - prepare-workspace
    - gitlog-upload

