---

- name: include variables for {{ zuul.pipeline }} pipeline
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ zuul.pipeline }}.yaml'
    - default.yaml

- name: 'Return registry location back to zuul for children jobs'
  zuul_return:
    data:
      contrail_docker_registry: "{{ nexus_registry_fqdn }}:{{ nexus_registry_port }}"
  delegate_to: localhost
