---

- name: include variables for {{ zuul.pipeline }} pipeline
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ zuul.pipeline }}.yaml'
    - default.yaml

- name: 'Set registry location for children jobs'
  set_fact:
    docker_registry_port: "{{ nexus_registry_port }}"
    contrail_docker_registry: "{{ nexus_registry_fqdn }}:{{ nexus_registry_port }}"
