---
- name: Ensure that all the required entries in /etc/hosts are present
  lineinfile:
    path: /etc/hosts
    line: "{{ item.address }} {{ item.fqdn }}"
  with_items: "{{ hosts_entries }}"
  become: true
  become_user: root

